# Pricing and risk-neutral dynamics


## SDF: Absence of Arbitrage Approach {#PricingAAO}

Consider a period of interest ${\mathcal T} = \{0,1,2,...,T^*\}$. As in Chapter \@ref(ChapterAffine), vector $w_t$ constitutes the new information in the economy at $t$. The historical, or physical, dynamics of $w_t$, $f(\underline{w_t})$, is defined by $f(w_{t+1}|\underline{w_t})$. The physical probability is denoted by $\mathbb{P}$. $L_{2t}, t \in {\mathcal T}$, is the (Hilbert) space of square integrate functions $g(\underline{w_t})$, and we have $L_{2t} \subset L_{2s}, t< s$.

### Existence and unicity of the SDF

:::{.hypothesis #Apricing1 name="Price existence and uniqueness"}
For any $\underline{w_t}$, there exists a unique $p_t[g(\underline{w_s})]$,
function of $\underline{w_t}$, price at $t$ of a payoff
$g(\underline{w_s})$ delivered at $s, \forall t \le s$.
:::

:::{.hypothesis #Apricing2 name="Linearity and continuity"}
For all $t < s$, $\underline{w_t}$, $g_1$, $g_2$, we have

* $p_t[\lambda_1 g_1(\underline{w_s}) + \lambda_2g_2(\underline{w_s})] = \lambda_1p_t[g_1(\underline{w_s})]+\lambda_2 p_t[g_2(\underline{w_s})]$,
* If $g_n(\underline{w_s}) 
\overset{L_{2s}}{\underset{n\rightarrow\infty}{\longrightarrow}} 0$, then $p_t[g_n(\underline{w_s})]
\underset{n\rightarrow\infty}{\longrightarrow} 0$.
:::

:::{.hypothesis #Apricing3 name="Absence of Arbitrage Opportunity (AAO)"}
At any $t$, it is impossible to constitute a portfolio of future payoffs, possibly modified at subsequent dates, such that:

* the price of the portfolio at $t$ is zero,
* payoffs at subsequent dates are $\ge 0$,
* there is at least one subsequent date $s$  such that the net payoff at $s$ is strictly positive with a non zero conditional probability at $t$.
:::

:::{.theorem #Riesz name="Riesz representation theorem"}

Under Assumptions \@ref(hyp:Apricing1) and \@ref(hyp:Apricing2), for all $\underline{w_t}$, and $s > t$, there exists $\mathcal{M}_{t,s}(\underline{w_s}) \in L_{2s}$, unique such that, $\forall g(\underline{w_s}) \in L_{2s}$,
$$
p_t[g(\underline{w_s})] = \mathbb{E}[\mathcal{M}_{t,s}(\underline{w_s})g(\underline{w_s})|\underline{w_t}].
$$
In particular the price at $t$ of a zero coupon bond maturing at $s$ is $\mathbb{E}(\mathcal{M}_{t,s}|\underline{w_t})$.
:::

:::{.proposition #PositivityM name="Positivity of M"}
If Assumption \@ref(hyp:Apricing3) is satisfied, then for all $t$ and $s$, $\mathbb{P}(\mathcal{M}_{t,s}>0|\underline{w_t})=1$.
:::
:::{.proof}
$\Leftarrow$ is obvious. If $\Rightarrow$ was not true, the payoff
$\textbf{1}_{\{\mathcal{M}_{t,s} \le 0\}}$, at $s$, would be such that:
$\mathbb{P}[\textbf{1}_{\{\mathcal{M}_{t,s} \le 0\}}=1|\underline{w_t}] > 0$ and $p_t[\textbf{1}_{\{\mathcal{M}_{t,s} \le 0\}}] = \mathbb{E}_t[\mathcal{M}_{t,s}\textbf{1}_{\{\mathcal{M}_{t,s} \le 0\}}] \le 0$.
:::

:::{.proposition #timeconsist name="Time consistency"}
For all $t < r < s$, we have $\mathcal{M}_{t,s} = \mathcal{M}_{t,r} \mathcal{M}_{r,s}$, which implies:

* $\mathcal{M}_{t,s} = \mathcal{M}_{t,t+1} \mathcal{M}_{t+1,t+2}\dots\mathcal{M}_{s-1,s}$
* $\mathcal{M}_{0,t} =  \Pi^{t-1}_{j=0} \mathcal{M}_{j,j+1}$ ($\mathcal{M}_{0,t}$ is called **pricing kernel**).
:::
:::{.proof}
Using Lemma \@ref(lem:sdf) we have:
\begin{eqnarray*}
p_t(g_s) &=& \mathbb{E}(\mathcal{M}_{t,s}g_s|\underline{w_t}) = \mathbb{E}(\mathcal{M}_{t,r} p_r(g_s)|\underline{w_t}) \\
&=& \mathbb{E}[\mathcal{M}_{t,r}\mathbb{E}(\mathcal{M}_{r,s} g_s|\underline{w_r})|\underline{w_t}] = \mathbb{E}(\mathcal{M}_{t,r} \mathcal{M}_{r,s} g_s|\underline{w_t}), \forall g, \forall \underline{w}_{t}
\end{eqnarray*}
and, therefore, $\mathcal{M}_{t,s} = \mathcal{M}_{t,r}\mathcal{M}_{r,s}$.
:::

:::{.lemma #sdf}
For any payoff $g_s$ at $s, p_t(g_s) = p_t[p_r(g_s)]$.
:::
:::{.proof}
If this was not true, we could construct a sequence of portfolios with a strictly positive payoff at $s$ with zero payoff at any other future date and with price zero at $t$, contradicting Assumption \@ref(hyp:Apricing3). Indeed, assuming, for instance, $p_t(g_s) > p_t[p_r(g_s)]$, the payoff at $s$ is defined by the following strategy: (i) at $t$: buy $p_r(g_s)$, (short) sell $g_s$, buy
$\frac{p_t(g_s)-p_t[p_r(g_s)]}{\mathbb{E}(\mathcal{M}_{t,s}|\underline{w_t})}$ zero-coupon bonds maturing at $s$, at global price zero, (ii) at $r$: buy $g_s$ and sell $p_r(g_s)$, generating a zero net payoff, (iii) at $s$, the net payoff is: $g_s-g_s+\frac{p_t(g_s)-p_t[p_r(g_s)]}{\mathbb{E}(\mathcal{M}_{t,s}|\underline{w_t})} > 0$.
:::


Consider an asset whose payoff, on date $s$, is $g(\underline{w_s})$. We have, $\forall t < s$:
\begin{equation}
\boxed{p_t[g(\underline{w_s})] = \mathbb{E}_t[\mathcal{M}_{t,t+1}...\mathcal{M}_{s-1,s}g(\underline{w_s})].}(\#eq:basic)
\end{equation}
In particular, since $L_{2,t+1}$ contains 1, the price at $t$ of a zero-coupon with residual maturity one is given by:
$$
B(t,1) := \mathbb{E}_t [\mathcal{M}_{t,t+1}].
$$
Denoting by $r_t$ the continously-compounded interest rate, defined through $B(t,1)=\exp(-r_{t})$, we get
$$
r_{t}=-\log \mathbb{E}_t [\mathcal{M}_{t,t+1}].
$$

:::{.definition #bankaccount name="Bank account"}
The bank account process $R_t$ is defined by $R_{t} \equiv \exp(r_0+...+r_{t-1}) =  \frac{1}{\mathbb{E}_0[ \mathcal{M}_{0,1}]\times ... \times \mathbb{E}_{t-1}
[\mathcal{M}_{t-1,t}]}$.

$R_t$ is the price of an investment initiated on date 0, when it was worth one dollar, and invested on each date at the risk-free rate (for one period).
:::

For any price process $p_t$, we have $p_t = \mathbb{E}_t(\mathcal{M}_{t,s} p_s)$ (with $s>t$), or $\mathcal{M}_{0,t} p_t = \mathbb{E}_t(\mathcal{M}_{0,s}p_s)$. That is, $\mathcal{M}_{0,t} p_t$ is a martingale. In particular $\mathcal{M}_{0,t} R_t$ is a martingale.

### Exponential affine SDF {#PricingAffine}

A specific (tractable) case is that of exponential affine SDF. Assume that
$$
\mathcal{M}_{t,t+1}(\underline{w_{t+1}}) = \exp[\alpha_t(\underline{w_t})'w_{t+1}+\beta_t(\underline{w_t})]
$$
where $\alpha_t$ defines the *prices of risk* or *sensitivity* vector. Using $\mathbb{E}_t[\mathcal{M}_{t,t+1}]=\exp(-r_{t})=\exp[\psi_t(\alpha_t)+\beta_t]$, we get:
\begin{equation}
\mathcal{M}_{t,t+1} = \exp[-r_{t}+\alpha'_tw_{t+1}-\psi_t(\alpha_t)].(\#eq:keySDF)
\end{equation}

:::{.example name="CCAPM/Power utility case"}

In the CCAPM-power-utility case (see Example \@ref(exm:CCAPM)), we have (Eq. \@ref(eq:powerutilSDF)):
$$
\mathcal{M}_{t,t+1} = \exp(\log \delta + \log q_t + \gamma \log   C_t - \log   q_{t+1} - \gamma  \log   C_{t+1}),
$$
where $q_t$ is the price of the consumption good, $C_t$ is the quantity consumed at $t$ and $\delta$ is the intertemporal discount rate.

Hence, in that case, $\mathcal{M}_{t,t+1}$ is exponential affine in $w_{t+1} = (\log q_{t+1}, \log C_{t+1})'$ (and its first lag).
:::


## The risk-neutral (R.N.) dynamics{#PricingRN}

The historical Dynamics is characterized by $f(\underline{w_{T^*}})$, or by the
sequence of conditional p.d.f. $f_{t+1}(w_{t+1}|\underline{w_t})$, or
$f_{t+1}(w_{t+1})$, with respect to (w.r.t.) some measure $\mu$.

We define the conditional risk-neutral p.d.f. w.r.t. the conditional historical probability. For that, we employ the Radon-Nikodym derivative $d^{\mathbb{Q}}_{t+1}(w_{t+1}|\underline{w_t})$:^[Of course, the conditional historical p.d.f. with respect to the conditional risk-neutral (R.N.) p.d.f. is:
$d_{t+1}(w_{t+1}) = \frac{1}{d^{\mathbb{Q}}_{t+1}(w_{t+1})}$ or $d_{t+1}(w_{t+1}) =
\frac{\exp(-r_{t})}{\mathcal{M}_{t,t+1}}$.]
$$
d^{\mathbb{Q}}_{t+1}(w_{t+1}|\underline{w_t}) =
\frac{\mathcal{M}_{t,t+1}(\underline{w_{t+1}})}{\mathbb{E}[\mathcal{M}_{t,t+1}(\underline{w_{t+1}})|\underline{w_t}]},
$$
or
$$
d^{\mathbb{Q}}_{t+1}(w_{t+1})=
\frac{\mathcal{M}_{t,t+1}}{\mathbb{E}_t(\mathcal{M}_{t,t+1})}=\exp(r_{t}) \mathcal{M}_{t,t+1}.
$$
In this context, the risk neutral conditional p.d.f. is:
\begin{eqnarray}
f^{\mathbb{Q}}_{t+1}(w_{t+1}) &=& f_{t+1}(w_{t+1})d^{\mathbb{Q}}_{t+1}(w_{t+1}) \nonumber \\
&=&f_{t+1} (w_{t+1}) \mathcal{M}_{t,t+1} (\underline{w_{t+1}}) \exp [r_{t} (\underline{w_t})].(\#eq:fQfP)
\end{eqnarray}

The p.d.f. of $\mathbb{Q}$ w.r.t. the historical dynamics $\mathbb{P}$ is:
$$
\xi_{T^*} =  \frac{d\mathbb{Q}}{d\mathbb{P}} =
\Pi^{T^{*}-1}_{t=0} d^{\mathbb{Q}}_{t+1}(w_{t+1}) =
\Pi^{T^{*}-1}_{t=0} \exp(r_{t}) \mathcal{M}_{t,t+1},
$$
and the p.d.f. of the R.N. distribution of $\underline{w_t}$, w.r.t. the corresponding historical distribution is:
$$
\xi_t= \Pi^{t-1}_{\tau=1}
d^{\mathbb{Q}}_{\tau+1}(w_{\tau+1})=\mathbb{E}_t\left(\frac{d\mathbb{Q}}{d\mathbb{P}}\right) = \mathbb{E}_t\xi_{T^*}.
$$
Therefore, $\xi_t$ is a $\mathbb{P}$-martingale.^[Indeed:
$$
\mathbb{E}_t \left( \frac{d\mathbb{Q}}{d\mathbb{P}}\right) = \Pi^{t-1}_{\tau = 1} d^{\mathbb{Q}}_{\tau + 1} (w_{\tau+1}) \mathbb{E}_t \left( d^{\mathbb{Q}}_{t+1} (w_{t+1}) \ldots d^{\mathbb{Q}}_{T^*} (w_{T^*})\right).
$$]

Consider the date-$t$ price of a payoff $g(\underline{w_s})$ at time $s>t$. An equivalent form of the pricing formula \@ref(eq:basic) is:
\begin{eqnarray*}
p_t[g(\underline{w_s})] &=& \mathbb{E}_t[\mathcal{M}_{t,t+1}...\mathcal{M}_{s-1,s}g(\underline{w_s})] \\
&=& \mathbb{E}^{\mathbb{Q}}_t[\exp(-r_{t}-...-r_{s-1})g(\underline{w_s})],
\end{eqnarray*}
or, with simpler notations:
$$
p_t = \mathbb{E}^{\mathbb{Q}}_t[\exp(-r_{t}-...-r_{s-1})p_s] = \mathbb{E}^{\mathbb{Q}}_t\left(\frac{R_t}{R_s} p_s\right),
$$
where $R_t$ is the *bank account*.

We also have $p_t/R_t = \mathbb{E}^{\mathbb{Q}}_t\left( p_s/R_s\right)$, that is, $p_t/R_t$ is a $\mathbb{Q}$-martingale. In particular $p_t = \exp(-r_{t})\mathbb{E}^{\mathbb{Q}}_t(p_{t+1})$, or, using the arithmetic return of any payoff $(p_{t+1}-p_t)/p_t$, and the arithmetic return of the riskless asset $r_{A,t+1}=\exp(r_{t})-1$, we get:
$$
\mathbb{E}^{\mathbb{Q}}_t\left(\frac{p_{t+1}-p_t}{p_t}\right)=r_{A,t}.
$$
Moreover the excess arithmetic return process $(p_{t+1}-p_t)/p_t-r_{A,t}$ is a $\mathbb{Q}$-martingale difference and, therefore, $\mathbb{Q}$-serially uncorrelated.

Let us consider the case of an exponential affine SDF $\mathcal{M}_{t,t+1}=\exp(\alpha'_t
w_{t+1}+\beta_t)$:
$$
d^{\mathbb{Q}}_{t+1}(w_{t+1}) = \frac{\mathcal{M}_{t,t+1}}{\mathbb{E}_t(\mathcal{M}_{t,t+1})} = \frac{\exp(\alpha'_t
w_{t+1}+\beta_t)}{\exp[\psi_t(\alpha_t)+\beta_t]} = \exp[\alpha'_t w_{t+1}-\psi_t(\alpha_t)]
$$
We then have that $d^{\mathbb{Q}}_{t+1}(w_{t+1})$ is also exponential affine. Moreover:
$$
f^{\mathbb{Q}}_{t+1} (w_{t+1}) = \frac{f_{t+1} (w_{t+1}) \exp (\alpha'_t w_{t+1})}{\varphi_t (\alpha_t)}.
$$
The previous equation shows that $f^{\mathbb{Q}}_{t+1}$ is the Esscher transform of $f_{t+1}$ evaluated at $\alpha_t$.

Let us know consider the Laplace transform of the conditional R.N. probability, $\varphi^{\mathbb{Q}}_t(u|\underline{w_t})$, also denoted by $\varphi^{\mathbb{Q}}_t(u)$. We have:
\begin{eqnarray*}
\varphi^{\mathbb{Q}}_t(u) &=& \mathbb{E}^{\mathbb{Q}}_t \exp(u' w_{t+1}) \\
&=& \mathbb{E}_t \exp[(u+\alpha_t)'w_{t+1}-\psi_t(\alpha_t)] \\
&=& \exp[\psi_t(u+\alpha_t)-\psi_t(\alpha_t)] =
\frac{\varphi_t(u+\alpha_t)}{\varphi_t(\alpha_t)}.
\end{eqnarray*}
Hence:
\begin{equation}
\boxed{\psi^{\mathbb{Q}}_t(u) = \psi_t(u+\alpha_t)-\psi_t(\alpha_t).}(\#eq:transfoPQ)
\end{equation}
We check that, if $\alpha_t=0$, $\psi^{\mathbb{Q}}_t=\psi_t$ (since $\psi_t(0)=0)$.

Moreover, putting $u=-\alpha_t$ in the expression of
$\psi^{\mathbb{Q}}_t(u)$ we get $\psi^{\mathbb{Q}}_t(-\alpha_t)=-\psi_t(\alpha_t)$,
 and, replacing $u$ by $u-\alpha_t$, we get:
$$
\boxed{\psi_t(u) = \psi^{\mathbb{Q}}_t(u-\alpha_t)-\psi^{\mathbb{Q}}_t(-\alpha_t).}
$$
Also:
\begin{equation*}
\left\{
\begin{array}{ccl}
d_{t+1}(w_{t+1}) &=& \exp[-\alpha'_t(w_{t+1})-\psi^{\mathbb{Q}}_t(-\alpha_t)] \\
d^{\mathbb{Q}}_{t+1}(w_{t+1}) &=& \exp[\alpha'_t(w_{t+1})+\psi^{\mathbb{Q}}_t(-\alpha_t)].
\end{array}
\right.
\end{equation*}

<!-- XXX* Back to the historical conditional probability: -->
<!-- $$ -->
<!-- d_{t+1}(w_{t+1}) = -->
<!-- \frac{1}{d^{\mathbb{Q}}_{t+1}(w_{t+1})} = \exp[-\alpha'_t -->
<!-- w_{t+1}+\psi_t(\alpha_t)], -->
<!-- $$ -->




## Typology of econometric asset-pricing models {#PricingTypology}


:::{.definition #typo name="Econometric Asset Pricing Model (EAPM)"}
An Econometric Asset Pricing Model (EAPM) is defined by the following functions:

* $r_{t}(\underline{w_t})$,
* $f(w_{t+1}|\underline{w_t}))$ [or $\psi_t(u)$],
* $\mathcal{M}_{t,t+1}(\underline{w_{t+1}})$,
* $f^{\mathbb{Q}}(w_{t+1}|\underline{w_t})$ [or $\psi^{\mathbb{Q}}_t(u)$].
:::

The previous functions have to to be specified and parameterized. They are linked by:
$$
f^{\mathbb{Q}}(w_{t+1}|\underline{w_t}) = f(w_{t+1}|\underline{w_t}) \mathcal{M}_{t,t+1}(\underline{w_{t+1}}) \exp[r_{t}(\underline{w_t}))].
$$

In the following, we present three ways of specifying an EAPM:

1. the direct modelling,
2. the R.N.-constrained direct modelling (or mixed modelling),
3. the back modelling.

We focus on the case where $\mathcal{M}_{t,t+1}$ is exponential affine, as in Eq. \@ref(eq:keySDF):
$$
\mathcal{M}_{t,t+1} (\underline{w_{t+1}}) = \exp\left\{ -r_{t} (\underline{w_t}) + \alpha'_t(\underline{w_t})w_{t+1} - \psi_t [\alpha_t (w_t)]\right\}.
$$
Once the short-term rate function $r_{t}(\underline{w_t})$ is specified, we have to specify $\psi_t$, $\alpha_t$, and $\psi^{\mathbb{Q}}_t$, that are linked by Eq. \@ref(eq:transfoPQ).

In all approaches, we have to specify the status of the short rate. The short rate $r_{t}$ is a function of $\underline{w_t}$, this function may be known or unknown by the econometrician. It is known in two cases: (a) $r_{t}$ is exogenous ($r_{t}(\underline{w_t})$ does not depend on $\underline{w_t}$) or (b) $r_{t}$ is a component of $w_t$. By contrast, if the function $r_{t} (\underline{w_t})$ is unknown, it has to be specified parametrically:
$$
\left\{ r_{t} (\underline{w_t}, \tilde{\theta}), \tilde{\theta}\in \tilde{\Theta} \right\},
$$
where $r_{t}(\bullet,\bullet)$ is a known function.

Let us now detail the three steps on which each of the three ways of defining an EAPM is based.

### The direct modelling {#DirectModeling}

* **Step 1 -- Specification of the historical dynamics**. We choose a parametric family for the conditional historical Log-Laplace transform $\psi_t(u|\underline{w_t})$: $\left\{ \psi_t (u|\underline{w_t} ; \theta_1), \theta_1 \in \Theta_1 \right\}$.
* **Step 2 -- Specification of the SDF**. Considering the affine specification of as Eq. \@ref(eq:keySDF), that is:
$$
\mathcal{M}_{t,t+1} (\underline{w_{t+1}}) = \exp\left\{ -r_{t}(\underline{w_t}, \tilde{\theta}) + \alpha'_t(\underline{w_t})w_{t+1} - \psi_t [\alpha_t (w_t)|\underline{w_t} ; \theta_1]\right\},
$$
we need to specifiy functions $r_{t}(\underline{w_t}, \tilde{\theta})$ and $\alpha_t(\underline{w_t})$. Assume that $\alpha_t(\underline{w_t})$ belongs to a parametric family: $\left\{ \alpha_t (\underline{w_t} ; \theta_2),\theta_2 \in \Theta_2 \right\}$.
We then have:
\begin{eqnarray*}
\mathcal{M}_{t,t+1}(\underline{w_{t+1}}, \theta) &=& \exp \left\{ - r_{t}
(\underline{w_t}, \tilde{\theta}) + \alpha'_t (\underline{w_t},\theta_2) w_{t+1} - \psi_{t} \left[ \alpha_t (\underline{w_t},
\theta_2) | \underline{w_t} ; \theta_1 \right] \right\},
\end{eqnarray*}
where $\theta = (\tilde{\theta}', \theta'_1,\theta'_2)' \in \tilde{\Theta}\times \Theta_1 \times \Theta_2 = \Theta$.
* **Step 3 -- Internal consistency conditions (ICC)**. For any payoff $g(\underline{w_s})$ settled at $s>t$, with price $p(\underline{w_t})$ at $t$ which is a known function of
$\underline{w_t}$, we must have:
\begin{equation*}
p(\underline{w_t}) = \mathbb{E} \left\{\mathcal{M}_{t,t+1} (\theta) \dots \mathcal{M}_{s-1,s} (\theta) g(\underline{w_s})  |  \underline{w_t},
\theta_1 \right\}    \forall \; \underline{w_t}, \theta.(\#eq:ICCgen)
\end{equation*}
These ICC pricing conditions may imply strong constraints on $\theta$. For instance, when components of $w_t$ are returns of some assets: if $w_{1,t} = \log(p_{1,t}/p_{1,t-1})$, then we must have $\mathbb{E}_t [\mathcal{M}_{t,t+1} \exp (e'_1 w_{t+1})]= 1$ (Euler equation). Or, in the case of interest rates with various maturities: if $w_{1,t} = -1/h\log B(t,h)$, then we must have $e'_1 w_{t} = - 1/h \log \mathbb{E}_t (\mathcal{M}_{t,t+1}\times \dots \times \mathcal{M}_{t+h-1,t+h})$.

The previous three steps imply the specification of the R.N. dynamics (according to Eq. \@ref(eq:transfoPQ)):
\begin{equation*}
\psi^{\mathbb{Q}} (u | \underline{w_t}, \theta_1, \theta_2) =
\psi_t \left[ u + \alpha_t (\underline{w_t}, \theta_2) |
\underline{w_t}, \theta_1 \right] - \psi_t \left[ \alpha_t
(\underline{w_t}, \theta_2) | \underline{w_t}, \theta_1
\right].
\end{equation*}


### The R.N.-constrained direct modelling (or mixed modelling)

* **Step 1 -- Specification of the physical dynamics**. We select a family $\{ \psi_t (u | \underline{w_t},\theta_1), \theta_1 \in \Theta_1 \}$.
* **Step 2 -- Specification of the risk-neutral dynamics**. We select a family $\{\psi^{\mathbb{Q}}_t (u | \underline{w_t},
\theta^*),\theta^* \in \Theta^* \}$ and, possibly, $\{r_{t}(\underline{w_t},\tilde{\theta}),\tilde{\theta}\in\tilde{\Theta}\}$.
* **Step 3 -- Internal Consistency Conditions (ICC)**. Once the parameterization $(\tilde{\theta},
\theta_1, \theta^*) \in \tilde{\Theta} \times \Theta^*_1$ is defined, ICCs may be imposed. For instance, if $w_{1,t} = \log(p_{1,t}/p_{1,t-1})$, then we must have $\exp(-r_t)\mathbb{E}^{\mathbb{Q}}_t \exp (e_{1}' w_{t+1}) = 1$. Or if $w_{1,t} = B(t,h)$, then $e_{1}' w_{t} = \mathbb{E}_t^{\mathbb{Q}} \exp(-r_t - \dots - r_{t+h-1})$.

The SDF is a by-product. If we want an exponential affine SDF, for any pair $(\psi^{\mathbb{Q}}_t, \psi_t)$ belonging to these families, there must exist a unique function $\alpha_t (\underline{w_t})$ denoted by $\alpha_t (w_t ; \theta_1, \theta^*)$, and satisfying:
\begin{equation*}
\psi^{\mathbb{Q}}_t (u | \underline{w_t}) = \psi_t \left[ u +
\alpha_t (w_t) | \underline{w_t} \right] - \psi_t \left[
\alpha_t (\underline{w_t}) | \underline{w_t} \right].
\end{equation*}

### Back modelling (based on three steps)

* **Step 1 -- Specification of the R.N. dynamics**, and possibly of $r_{t}(\underline{w_t})$]: $\psi^{\mathbb{Q}}_t (u | \underline{w_t}; \theta^*_1)$.
* **Step 2 -- Internal consistency conditions (ICC)**, if relevant, are taken into account:
\begin{equation*}
\begin{array}{lll}
&& p(\underline{w_t}) = \mathbb{E}^{\mathbb{Q}}_t \left[ \exp (-r_{t} (\underline{w_t},\tilde{\theta}) - \dots - r_{s-1} (\underline{w_s}, \tilde{\theta}))g(\underline{w_s}) | \underline{w_t} , \theta^*_1\right] ,\\
&& \forall    \underline{w_t} , \tilde{\theta} , \theta^*_1.
\end{array}
\end{equation*}
* **Step 3 -- Choice of the specification of the prices of risk**. One chooses function $\alpha_t(\underline{w_t})$ without any constraint; this amounts to defining the family $\{ \alpha_t (\underline{w_t}, \theta^*_2), \theta^*_2\in \Theta^*_2 \}$.

The historical dynamics is obtained as a by-product. Indeed:
\begin{equation*}
\psi_t(u | \underline{w_t} ; \theta^*_1, \theta^*_2) = \psi_t^{\mathbb{Q}}\left[ u -\alpha_t (\underline{w_t}, \theta^*_2)|\underline{w_t} ; \theta^*_1 \right] -\psi^{\mathbb{Q}}_t \left[- \alpha_t (\underline{w_t}, \theta^*_2) | \underline{w_t},\theta^*_1 \right].
\end{equation*}

